apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: 3x-ui-tls-passthrough
  namespace: 3x-ui-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`px.awspythoncourses.org`)
      services:
        - name: x3-ui-svc
          port: 2053
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: 3x-ui-trojan
  namespace: 3x-ui-system
spec:
  entryPoints:
    - grpc_real
  routes:
    - match: HostSNI(`quiz.awspythoncourses.org`)
      services:
        - name: x3-ui-svc
          port: 2083
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: 3x-ui-reality
  namespace: 3x-ui-system
spec:
  entryPoints:
    - vless_gh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: x3-ui-svc
          port: 36028
  tls:
    passthrough: true