apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: 3x-ui-tls-passthrough
  namespace: 3x-ui-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`px.awspythoncourses.org`)
      services:
        - name: x3-ui-svc
          port: 2053
  tls:
    passthrough: true

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 3x-ui-web-ui
  namespace: 3x-ui-system
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - px.awspythoncourses.org
      secretName: px-tls
  rules:
    - host: px.awspythoncourses.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: x3-ui-svc
                port:
                  number: 8080
