apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: px-tls
  namespace: 3x-ui-system
spec:
  secretName: px-tls
  commonName: px.awspythoncourses.org
  dnsNames:
    - px.awspythoncourses.org
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quiz-tls
  namespace: traefik-system
spec:
  secretName: quiz-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: quiz.px.awspythoncourses.org
  dnsNames:
    - quiz.px.awspythoncourses.org
