apiVersion: v1
kind: Service
metadata:
  name: x3-ui-svc
  namespace: 3x-ui-system
spec:
  selector:
    app: 3x-ui
  ports:
    - name: panel
      port: 2053
      targetPort: 2053
      protocol: TCP
    - name: vpn
      port: 27282
      targetPort: 27282
      protocol: TCP