apiVersion: v1
kind: Service
metadata:
  name: x3-ui-svc
  namespace: 3x-ui-system
spec:
  selector:
    app: 3x-ui
  ports:
    - name: panel
      port: 2053
      targetPort: 2053
      protocol: TCP
    - name: grpcreal
      port: 2083
      targetPort: 2083
      protocol: TCP
    - name: vlessgh
      port: 36028
      targetPort: 36028
      protocol: TCP
    - name: trojangoogle
      port: 49245
      targetPort: 49245
      protocol: TCP
