apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: px-tls
  namespace: remnawave-ns
spec:
  secretName: px-tls
  commonName: px.awspythoncourses.org
  dnsNames:
    - px.awspythoncourses.org
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
