apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remnawave-db-pvc
  namespace: remnawave-ns
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: remnawave-db
  namespace: remnawave-ns
spec:
  serviceName: remnawave-db
  replicas: 1
  selector:
    matchLabels:
      app: remnawave-db
  template:
    metadata:
      labels:
        app: remnawave-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: remnawave
            - name: POSTGRES_USER
              value: remnawave
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: remnawave-db-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: remnawave-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: remnawave-db
  namespace: remnawave-ns
spec:
  selector:
    app: remnawave-db
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
