apiVersion: v1
kind: Secret
metadata:
  name: remnawave-env
  namespace: remnawave-ns
type: Opaque
stringData:
  FRONT_END_DOMAIN:   "px.awspythoncourses.org"
  SUB_PUBLIC_DOMAIN:  "px.awspythoncourses.org/api/sub"
  REDIS_HOST:         "remnawave-redis"
  REDIS_PORT:         "6379"